baseURL = "https://heiss.github.io/"
languageCode = "en—us"
title = "Netzmuffel - Alles und Nichts"
theme = "blank"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
    post = "/post/:title"

[[menu.main]]
    name = "Start"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Über"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Feed"
    url = "/index.xml"
    weight = 5

[author]
    name = "PhysicX"

[params]
    description = "Ein bisschen hiervon und davon."
    show_posts = 10
    max_len = 28